on: push
jobs:
  pypi-publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: PyPi
      url: https://pypi.org/p/arkush
    permissions:
      id-token: write
    steps:
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4.1
      - name: Build Package
        run: pdm build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
